### PR TITLE
Add a lot more features

### PR DESCRIPTION
**Pull request by CheatMaker**
Added Bhop

### CODE REVIEW

**Comment by sigmaclientwastaken** [comment]
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

no
just no

**Comment by DiamondCoder1000** [comment]
> aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
> 
> no just no

u got a problem?

**Comment by sigmaclientwastaken** [comment]
> > aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
> > no just no
> 
> u got a problem?

yes, literally everything

- you deserve to be murdered for that antibot
- kys we dont need another terrible aura
- stop pasting a client worse than fdp
- you used update() meaning you never even tested this
- Hypixel max settings are not using that Speed
- noClip bhop im gonna jump off a bridge

**Comment by DiamondCoder1000** [comment]
> 
bro chill

**Comment by NerdHaxx** [comment]
hmm that killaura suspiciously looks like a skid from ravenN+

**Comment by BerryPGz** [comment]
> hmm killaura & antibot suspiciously look like a skid from ravenN+
> 
> bruv u just copied SleepyFishYT's code and added a few lines that probably dont even matter

bro retard or smth? of they copy from ravenB++ they even admit it a skid in there website

**Comment by EbDeVV** [comment]
> hmm killaura & antibot suspiciously look like a skid from ravenN+
> 
> bruv u just copied SleepyFishYT's code and added a few lines that probably dont even matter

Cheating com at it's finest :)

**Comment by DiamondCoder1000** [comment]
> hmm killaura & antibot suspiciously look like a skid from ravenN+
> 
> bruv u just copied SleepyFishYT's code and added a few lines that probably dont even matter

skidding fun :)

**Comment by yorik100** [comment]
AntiBot "if(n.length() < 3) return true", wouldn't work on legit people with 2 characters name

**Pull request closed without merging**
